sudo: required

script:
    - deno run app test --allow-env tests/version.test.ts
 
deploy:
    provider: heroku
    api_key:
        secure: $HEROKU_AUTH_TOKEN
    app: agnusapi
    on:
        branch: master