sudo: required

services:
    - docker

before_install:
    - docker build -t app .

script:
    - docker run app test --allow-env tests/version.test.ts
 
deploy:
    provider: heroku
    api_key:
        secure: "$HEROKU_ACCESS_KEY_ID"
    on:
        branch: master