sudo: required

services:
    - docker

before_install:
    - docker build -t app .

script:
    - docker run app test --allow-env tests/version.test.ts
 
deploy:
    provider: heroku
    api_key: $HEROKU_AUTH_TOKEN
    app: agnusapi
